# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-24 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areas',
            options={'verbose_name_plural': '区'},
        ),
        migrations.AlterModelOptions(
            name='provinces',
            options={'verbose_name_plural': '省'},
        ),
        migrations.AddField(
            model_name='faultrecord',
            name='tag',
            field=models.ManyToManyField(blank=True, default='', null=True, to='record.RecordTags', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='faultrecord',
            name='ps',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
