# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_auto_20180124_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faultrecord',
            name='tag',
            field=models.ManyToManyField(blank=True, to='record.RecordTags', verbose_name='标签'),
        ),
    ]
