# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-09 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_auto_20180128_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faultrecord',
            name='handling_method',
            field=models.TextField(blank=True, null=True, verbose_name='处理办法'),
        ),
    ]
