# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 14:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='项目名')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='项目说明')),
                ('is_use', models.BooleanField(default=True, verbose_name='是否启用')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('add_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='添加者')),
            ],
            options={
                'verbose_name_plural': '项目',
            },
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='分类名')),
                ('dev_group', models.CharField(blank=True, max_length=64, null=True, verbose_name='开发团队Leader')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='项目分类说明')),
                ('is_use', models.BooleanField(default=True, verbose_name='是否启用')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('add_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='添加者')),
            ],
            options={
                'verbose_name_plural': '项目类别',
            },
        ),
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ask_user', models.CharField(max_length=64, verbose_name='发起者')),
                ('op_user', models.CharField(max_length=64, verbose_name='运维')),
                ('dba_user', models.CharField(max_length=64, verbose_name='DBA')),
                ('app_server', models.CharField(max_length=256, verbose_name='应用服务器')),
                ('app_desc', models.TextField(blank=True, null=True, verbose_name='应用服务器备注')),
                ('data_server', models.CharField(max_length=256, verbose_name='数据库服务器')),
                ('data_desc', models.TextField(blank=True, null=True, verbose_name='数据库服务器备注')),
                ('run_env', models.CharField(max_length=256, verbose_name='运行环境')),
                ('doc', models.TextField(verbose_name='运维部署文档')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('add_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='添加者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_mana.Project', verbose_name='项目')),
            ],
            options={
                'verbose_name_plural': '项目详情',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='cate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_mana.ProjectCategory', verbose_name='所属分类'),
        ),
    ]
