# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-05 14:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_mana', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_title', models.CharField(max_length=128, unique=True, verbose_name='文章标题')),
                ('doc_content', models.TextField(verbose_name='文章正文')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('doc_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name_plural': '安装文档',
            },
        ),
        migrations.CreateModel(
            name='InstallDocTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='标签名称')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name_plural': '文档标签',
            },
        ),
        migrations.AddField(
            model_name='installdoc',
            name='doc_tag',
            field=models.ManyToManyField(blank=True, to='project_mana.InstallDocTag', verbose_name='文档标签'),
        ),
    ]
