# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-09 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_deploy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployrecord',
            name='deploy_time',
            field=models.DateTimeField(verbose_name='发布时间'),
        ),
    ]
