# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-06 17:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20180206_1452'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='serverinfo',
            unique_together=set([]),
        ),
    ]
