# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-07 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_auto_20180206_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverinfo',
            name='port',
            field=models.SmallIntegerField(default=22, verbose_name='远程端口'),
        ),
    ]
