# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-07 15:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset', '0004_serverinfo_port'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsshHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_ip', models.GenericIPAddressField(verbose_name='服务器IP')),
                ('server_user', models.CharField(max_length=32, verbose_name='登录用户')),
                ('user_ip', models.GenericIPAddressField(verbose_name='用户IP')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '远程记录表',
                'verbose_name_plural': '远程记录表',
            },
        ),
    ]
