# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-07 17:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset', '0005_websshhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_ip', models.GenericIPAddressField(verbose_name='外网IP')),
                ('out_port', models.SmallIntegerField(verbose_name='外网端口')),
                ('in_ip', models.GenericIPAddressField(verbose_name='内网IP')),
                ('in_port', models.SmallIntegerField(verbose_name='内网端口')),
                ('ask_user', models.CharField(max_length=32, verbose_name='申请人')),
                ('use_for', models.CharField(max_length=128, verbose_name='用途')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('stop_time', models.DateTimeField(verbose_name='结束时间')),
                ('status', models.SmallIntegerField(choices=[(0, '已到期'), (1, '正常')], default=1, verbose_name='映射状态')),
                ('ps', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('handling_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
            ],
            options={
                'verbose_name': '端口映射表',
                'verbose_name_plural': '端口映射表',
            },
        ),
    ]
