# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserDepartment', verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserPosition', verbose_name='职位'),
        ),
    ]
