# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-04 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180102_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nick_name',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='中文名'),
        ),
    ]
