# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-04 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180104_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='其他'),
        ),
    ]
