# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-05 16:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=20, null=True, verbose_name='类型')),
                ('agent', models.CharField(blank=True, max_length=50, null=True, verbose_name='客户端')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='登录区域')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='客户端IP')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户登录信息',
                'verbose_name_plural': '用户登录信息',
            },
        ),
    ]
