# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-05 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userloginrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloginrecord',
            name='agent_system',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='客户端系统'),
        ),
    ]
