# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-05 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20180105_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userloginrecord',
            name='agent_system',
        ),
        migrations.AlterField(
            model_name='userloginrecord',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='登录区域'),
        ),
    ]
